# Generated by Django 5.0.6 on 2024-06-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovelData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=2),
        ),
    ]
